exports.run = (client, message, Discord) => {
    const embed = new Discord.RichEmbed()
        .setAuthor("Commands", client.user.displayAvatarURL)
        .setDescription(`Use \`--help <commandname>\` for more details.`)
        .setColor('B6D6E7')
        .setThumbnail(client.user.displayAvatarURL)
        .setFooter("Any message from me can be removed by reacting with a ⏲ emoji.")
        .addField("__Info:__", "`commands` `help` `nextbong` `setbong` `support`")
        .addField("__Utility:__", "`colour` `time` `translate` `weather`", true)
        .addField("__Search:__", "`img` `wiki` `urban` `youtube`", true)
        .addField("__Fun:__", "`8ball` `cat` `f` `meme` `rightthere` `shut` `smug` `talk`")
        .addField("__Memes:__", "`bonzi` `byemom` `disabled` `plsshut` `thesearch` `triggered` `walk`")
        .addField("__2D NSFW:__", "`danbooru` `hentai` `hentaiirl` `neko` `rule34` `safebooru`")
        .addField("__3D NSFW:__", "`ass` `boobs` `nsfw` `nsfwgif`")
    return message.channel.send({embed}).then(m=>m.react("⏲"))
}